project:
  type: website
  output-dir: docs

website:
  title: "Large Language Models Complete Tutorial"
  description: "A comprehensive guide to Large Language Models"
  
  navbar:
    left:
      - href: index.md
        text: Home
      - text: "Chapters"
        menu:
          - href: Chapter_01_Introduction_LLMs.md
            text: "01 - Introduction to LLMs"
          - href: Chapter_02_Math_Foundations.md
            text: "02 - Mathematical Foundations"
          - href: Chapter_03_NLP_Fundamentals.md
            text: "03 - NLP Fundamentals"
          - href: Chapter_04_Transformer_Architecture.md
            text: "04 - Transformer Architecture"
          - href: Chapter_05_Modern_Transformer_Variants_Complete.md
            text: "05 - Modern Transformer Variants"
          - href: Chapter_08_Fine_Tuning.md
            text: "08 - Fine-Tuning"
          - href: Chapter_09_Alignment_RLHF.md
            text: "09 - Alignment & RLHF"
          - href: Chapter_10_Prompting_InContext_Learning.md
            text: "10 - Prompting & In-Context Learning"
          - href: Chapter_11_RAG.md
            text: "11 - Retrieval-Augmented Generation"
          - href: Chapter_12_LLM_Agents_Tool_Use.md
            text: "12 - LLM Agents & Tool Use"
          - href: Chapter_13_Optimization_Inference.md
            text: "13 - Optimization & Inference"
          - href: Chapter_14_Production_Deployment.md
            text: "14 - Production & Deployment"
          - href: Chapter_15_Multimodal_LLMs.md
            text: "15 - Multimodal LLMs"
          - href: Chapter_16_Evaluation_Benchmarking.md
            text: "16 - Evaluation & Benchmarking"
          - href: Chapter_17_Cutting_Edge_Research_Future.md
            text: "17 - Cutting-Edge Research & Future"
  
  search: true

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    toc: true
    toc-depth: 3
    code-copy: true
    code-fold: false
    highlight-style: github
    css: custom.css

